webApp/website/auth.py
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import Location, User
from website import db
from sqlalchemy import func


auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        user = User.query.filter_by(email = email).first()
        if user:
            if check_password_hash(user.password, password):
                login_user(user, remember=True)
                # Loads the user's favorites or ''None' until selected
                favForecast1 = Location.query.filter_by(name=current_user.fav1).scalar()
                favForecast2 = Location.query.filter_by(name=current_user.fav2).scalar()
                favForecast3 = Location.query.filter_by(name=current_user.fav3).scalar()
                favForecast4 = Location.query.filter_by(name=current_user.fav4).scalar()
                # If there are multiple location with the same forecasted amount
                # the deepest location will be the first one in the list
                # Gets the deepest locations for each pass.
                # Get maximum depth forecasted for ikon
                deepestIkon = db.session.query(func.max(Location.forecast0)).filter(Location.ikon == 1).scalar()
                # Get the first of the locations that has the maximum depth as the days forecast for ikon if multiples
                deepIkon = Location.query.filter_by(forecast0 = deepestIkon).filter(Location.ikon == 1).all()[0]
                # Get maximum depth forecasted for epic
                deepestEpic = db.session.query(func.max(Location.forecast0)).filter(Location.epic == 1).scalar()
                # Get the first of the locations that has the maximum depth as the days forecast for epic if multiples
                deepEpic = Location.query.filter_by(forecast0 = deepestEpic).filter(Location.epic == 1).all()[0]
                # Get maximum depth forecasted for mountain collective
                deepestMC = db.session.query(func.max(Location.forecast0)).filter(Location.mc == 1).scalar()
                # Get the first of the locations that has the maximum depth as the days forecast for mountain collective if multiples
                deepMC = Location.query.filter_by(forecast0 = deepestMC).filter(Location.mc == 1).all()[0]
                # Get maximum depth forecasted for powder alliance
                deepestPowder = db.session.query(func.max(Location.forecast0)).filter(Location.powder == 1).scalar()
                # Get the first of the locations that has the maximum depth as the days forecast for powder alliance if multiples
                deepPowder = Location.query.filter_by(forecast0 = deepestPowder).filter(Location.powder == 1).all()[0]
                # Get maximum depth forecasted for indy
                deepestIndy = db.session.query(func.max(Location.forecast0)).filter(Location.indy == 1).scalar()
                # Get the first of the locations that has the maximum depth as the days forecast for indy if multiples
                deepIndy = Location.query.filter_by(forecast0 = deepestIndy).filter(Location.indy == 1).all()[0]
                return render_template("favorites.html", boolean=True, favorite1 = favForecast1, favorite2 = favForecast2, favorite3 = favForecast3, favorite4 = favForecast4, deepIkon = deepIkon, deepEpic = deepEpic, deepMC = deepMC, deepPowder = deepPowder, deepIndy = deepIndy)
            else:
                flash('Email or Password not recognized!', category = 'error')
        else:
            flash('Email or Password not recognized!', category = 'error')
    return render_template("login.html")

@auth.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    flash('You have logged out.', category='success')
    return redirect(url_for('views.home'))

@auth.route('/register', methods=['GET', 'POST'])
def register():
    # Get form info to check and add user to db
    if request.method == 'POST':
        email = request.form.get('email')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        
        # Check for previous registration
        user = User.query.filter_by(email = email).first()
        # Check user input for validity
        if user:
            flash('Email already registered', category = 'error')
        elif (len(email) < 4):
            flash('Please enter a valid email', category = 'error')
        elif (len(password1) < 8):
            flash("Password must be at least 8 characters", category = 'error')
        elif (password1 != password2):
            flash('Passwords do not match.', category = 'error')
        else:
            # create a new user with form info
            new_user = User(email=email, password=generate_password_hash(password1, method='sha256'))
            db.session.add(new_user) # add the user to the db
            db.session.commit() # commit changes to db
            login_user(new_user, remember = True) # Log new user in 
            flash('Account created!', category='success')
            return redirect(url_for('views.setfavorites'))
    
    return render_template("register.html")


webApp/website/views.py
from flask import Blueprint, render_template, request, flash, redirect, session
from flask_login import login_required, current_user
from .models import Location
from website import db
from sqlalchemy import func, desc

views = Blueprint('views', __name__)


@views.route('/', methods=['GET', 'POST'])
def home():
    # If there are multiple location with the same forecasted amount
    # the deepest location will be the first one in the list
    # Gets the location that has the deepest forecast for the day
    maxSnow = db.session.query(func.max(Location.forecast0)).scalar()
    # Get the first of the locations that has the maximum depth as the days forecast if multiples
    deepest = Location.query.filter_by(forecast0 = maxSnow).all()[0]
    
    # Gets the deepest locations for each pass.
    # Get maximum depth forecasted for ikon
    deepestIkon = db.session.query(func.max(Location.forecast0)).filter(Location.ikon == 1).scalar()
    # Get the first of the locations that has the maximum depth as the days forecast for ikon if multiples
    deepIkon = Location.query.filter_by(forecast0 = deepestIkon).filter(Location.ikon == 1).all()[0]
    # Get maximum depth forecasted for epic
    deepestEpic = db.session.query(func.max(Location.forecast0)).filter(Location.epic == 1).scalar()
    # Get the first of the locations that has the maximum depth as the days forecast for epic if multiples
    deepEpic = Location.query.filter_by(forecast0 = deepestEpic).filter(Location.epic == 1).all()[0]
    # Get maximum depth forecasted for mountain collective
    deepestMC = db.session.query(func.max(Location.forecast0)).filter(Location.mc == 1).scalar()
    # Get the first of the locations that has the maximum depth as the days forecast for mountain collective if multiples
    deepMC = Location.query.filter_by(forecast0 = deepestMC).filter(Location.mc == 1).all()[0]
    # Get maximum depth forecasted for powder alliance
    deepestPowder = db.session.query(func.max(Location.forecast0)).filter(Location.powder == 1).scalar()
    # Get the first of the locations that has the maximum depth as the days forecast for powder alliance if multiples
    deepPowder = Location.query.filter_by(forecast0 = deepestPowder).filter(Location.powder == 1).all()[0]
    # Get maximum depth forecasted for indy
    deepestIndy = db.session.query(func.max(Location.forecast0)).filter(Location.indy == 1).scalar()
    # Get the first of the locations that has the maximum depth as the days forecast for indy if multiples
    deepIndy = Location.query.filter_by(forecast0 = deepestIndy).filter(Location.indy == 1).all()[0]

    # Lets user select a location to see the forecast    
    locations = Location.query.all() # Stores all locations in array
    chosenLocal = request.form.get('chosen') # Gets the selection from the user
    chosen = Location.query.filter_by(name=chosenLocal).scalar() # Gets the forecast for the chosec location

    return render_template("home.html", user=current_user, deepest = deepest, locations=locations, chosenLocal = chosen, deepIkon = deepIkon, deepEpic = deepEpic, deepMC = deepMC, deepPowder = deepPowder, deepIndy = deepIndy)

@views.route('/search', methods=['GET', 'POST'])
@login_required
def search():
    searchStyles = ["Pass", "Reigon", "State"]  # Ways to search
    passes = ["Ikon", "Epic", "Mountain Collective", "Powder Alliance", "Indy"] # Passes to search
    if request.method == 'POST':
        searchStyle = "/search" + request.form.get('style') # Creates the path for the redirect from users chosen style
        session['searchStyle'] = request.form.get('style') # Session variable to carry selected search through redirect
        return redirect(searchStyle) # Redirects to the appropriate page for selected search
    else:
        # Return the page to allow the user to select style to search
        return render_template("search.html", user=current_user, searchStyles = searchStyles)

@views.route('/searchPass', methods=['GET', 'POST'])
@login_required
def searchPass():
    passes = ["Ikon", "Epic", "Mountain Collective", "Powder Alliance", "Indy"] # Passes to search
    if request.method == 'POST':
        session['searchParamater'] = request.form.get('selectedPass') # Session variable to carry selected pass through redirect
        return redirect('/searchResults')
    else:
        # Return the page to allow the user to select pass
        return render_template("searchPass.html", passes = passes)

@views.route('/searchState', methods=['GET', 'POST'])
@login_required
def searchState():
    # states to search by
    states = ["AK", "AZ", "CA", "CO", "CT", "ID", "IL", "IN", "MA", "MD", "ME", "MI", "MN", "MO", "MT", "NC", "ND", "NH", "NJ", "NM", "NV", "NY", "OH", "OR", "PA", "RI", "SD", "TN", "UT", "VA", "VT", "WA", "WI", "WV", "WY"]
    if request.method == 'POST':
        session['searchParamater'] = request.form.get('selectedState') # Session variable to carry selected pass through redirect
        return redirect('/searchResults')
    else:
        # Return the page to allow the user to select state
        return render_template("searchState.html", states = states)

@views.route('/searchReigon', methods=['GET', 'POST'])
@login_required
def searchReigon():
    # reigons to search by
    reigons = ["MidWest", "NorthEast", "Rockies", "SouthEast", "West"]
    if request.method == 'POST':
        session['searchParamater'] = request.form.get('selectedReigon') # Session variable to carry selected pass through redirect
        return redirect('/searchResults')
    else:
        # Return the page to allow the user to select reigon
        return render_template("searchReigon.html", reigons = reigons)

@views.route('/searchResults')
@login_required
def searchResults():
    # Gets the 4 deepest locations filtered by searchStyle
    # Get search by pass Pass results
    if (session['searchStyle'] == 'Pass'):
        searchParamater = session['searchParamater']
        if searchParamater == 'Ikon':
            query = Location.query.filter(Location.ikon == 1).order_by(desc(Location.forecast0)).all()[0:4]
        elif searchParamater == 'Epic':
            query = Location.query.filter(Location.epic == 1).order_by(desc(Location.forecast0)).all()[0:4]
        elif searchParamater == 'Mountain Collective':
            query = Location.query.filter(Location.mc == 1).order_by(desc(Location.forecast0)).all()[0:4]
        elif searchParamater == 'Powder Alliance':
            query = Location.query.filter(Location.powder == 1).order_by(desc(Location.forecast0)).all()[0:4]
        elif searchParamater == 'Indy':
            query = Location.query.filter(Location.indy == 1).order_by(desc(Location.forecast0)).all()[0:4]
        return render_template("searchResults.html", query = query, searchParamater = searchParamater)
    # Get search by Reigon reuslts
    if(session['searchStyle'] == 'Reigon'):
        searchParamater = ""
        searchParamater = session['searchParamater']
        query = Location.query.filter(Location.reigon == searchParamater).order_by(desc(Location.forecast0)).all()[0:4]
        return render_template("searchResults.html", query = query, searchParamater = searchParamater)
    # Get search by State results
    if(session['searchStyle'] == 'State'):
        searchParamater = ""
        searchParamater = session['searchParamater']
        query = Location.query.filter(Location.state == searchParamater).order_by(desc(Location.forecast0)).all()[0:4]
        return render_template("searchResults.html", query = query, searchParamater = searchParamater)



@views.route('/favorites')
@login_required
def favorites():
     # Gets the deepest locations for each pass.
    # Get maximum depth forecasted for ikon
    deepestIkon = db.session.query(func.max(Location.forecast0)).filter(Location.ikon == 1).scalar()
    # Get the first of the locations that has the maximum depth as the days forecast for ikon if multiples
    deepIkon = Location.query.filter_by(forecast0 = deepestIkon).filter(Location.ikon == 1).all()[0]
    # Get maximum depth forecasted for epic
    deepestEpic = db.session.query(func.max(Location.forecast0)).filter(Location.epic == 1).scalar()
    # Get the first of the locations that has the maximum depth as the days forecast for epic if multiples
    deepEpic = Location.query.filter_by(forecast0 = deepestEpic).filter(Location.epic == 1).all()[0]
    # Get maximum depth forecasted for mountain collective
    deepestMC = db.session.query(func.max(Location.forecast0)).filter(Location.mc == 1).scalar()
    # Get the first of the locations that has the maximum depth as the days forecast for mountain collective if multiples
    deepMC = Location.query.filter_by(forecast0 = deepestMC).filter(Location.mc == 1).all()[0]
    # Get maximum depth forecasted for powder alliance
    deepestPowder = db.session.query(func.max(Location.forecast0)).filter(Location.powder == 1).scalar()
    # Get the first of the locations that has the maximum depth as the days forecast for powder alliance if multiples
    deepPowder = Location.query.filter_by(forecast0 = deepestPowder).filter(Location.powder == 1).all()[0]
    # Get maximum depth forecasted for indy
    deepestIndy = db.session.query(func.max(Location.forecast0)).filter(Location.indy == 1).scalar()
    # Get the first of the locations that has the maximum depth as the days forecast for indy if multiples
    deepIndy = Location.query.filter_by(forecast0 = deepestIndy).filter(Location.indy == 1).all()[0]
    
    # Gets the forecast for the users 4 selected favorites
    favForecast1 = Location.query.filter_by(name=current_user.fav1).scalar()
    favForecast2 = Location.query.filter_by(name=current_user.fav2).scalar()
    favForecast3 = Location.query.filter_by(name=current_user.fav3).scalar()

webApp/website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />

    <title>{% block title %}BaseTemplate{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <a href="{{ url_for('views.home')}}" class="navbar-brand"><img src="{{url_for('static', filename='logo.png')}}" width ="50" height = "50"></a>
      <a class="navbar-brand" href="{{ url_for('views.home')}}">Powder-Bot</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
     
        </ul>
        {% if not current_user.is_authenticated %}
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.register') }}"
              >Sign-Up</a
            >
          </li>
        </ul>
        {% else %}
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('views.favorites') }}"
              >Favorites <span class="sr-only">(current)</span></a
            >
          </li>
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{{ url_for('views.search') }}"
                >Search <span class="sr-only">(current)</span></a
              >
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.logout') }}"
              >Logout</a
            >
          </li>
        </ul>
        {% endif %}
      </div>
    </nav>


    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">
      <br />
      {% block content %} {% endblock %}
    </div>
      
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

  </body>
  <footer>
    {% block footer %} Forecast data provided by <a href="https://openweathermap.org/">Open Weather<a>, <a href="https://www.weatherapi.com/">Weather API</a>, <a href="https://www.weatherbit.io/">Weatherbit</a>, <a href="https://www.visualcrossing.com/">Visual Crossing</a>
    <br />
    <a href = "mailto: pocahontaspowderbot@gmail.com "><img src="{{url_for('static', filename='emailIcon.png')}}" width ="50" height = "50">Contact</a>
    {% endblock %}
  </footer>
  <style>
    body {
      background-color: #212121;
      color: white;
    }
  </style>
</html>

webApp/website/templates/favorites.html
{% extends 'base.html' %} {% block title %}Favorites{% endblock %} {% block
content %}
<h1 style="text-align: center">Favorites</h1>
<div class="table-responsive" style="overflow-x: auto">
  <table class="table table-striped table-dark table-bordered">
    <thead class="thead-light">
      <tr>
        <th scope="col">Mountain</th>
        <th scope="col"><p id="date"></p></th>
        <th scope="col"><p id="date1"></p></th>
        <th scope="col"><p id="date2"></p></th>
        <th scope="col"><p id="date3"></p></th>
        <th scope="col"><p id="date4"></p></th>
        <th scope="col"><p id="date5"></p></th>
        <th scope="col"><p id="date6"></p></th>
        <th scope="col"><p id="date7"></p></th>
        <th scope="col"><p id="date8"></p></th>
        <th scope="col"><p id="date9"></p></th>
        <th scope="col"><p id="date10"></p></th>
        <th scope="col"><p id="date11"></p></th>
        <th scope="col"><p id="date12"></p></th>
        <th scope="col"><p id="date13"></p></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">{{ current_user.fav1 }}</th>
        <td>{{favorite1.forecast0}}</td>
        <td>{{favorite1.forecast1}}</td>
        <td>{{favorite1.forecast2}}</td>
        <td>{{favorite1.forecast3}}</td>
        <td>{{favorite1.forecast4}}</td>
        <td>{{favorite1.forecast5}}</td>
        <td>{{favorite1.forecast6}}</td>
        <td>{{favorite1.forecast7}}</td>
        <td>{{favorite1.forecast8}}</td>
        <td>{{favorite1.forecast9}}</td>
        <td>{{favorite1.forecast10}}</td>
        <td>{{favorite1.forecast11}}</td>
        <td>{{favorite1.forecast12}}</td>
        <td>{{favorite1.forecast13}}</td>
      </tr>
      <tr>
        <th scope="row">{{ current_user.fav2 }}</th>
        <td>{{favorite2.forecast0}}</td>
        <td>{{favorite2.forecast1}}</td>
        <td>{{favorite2.forecast2}}</td>
        <td>{{favorite2.forecast3}}</td>
        <td>{{favorite2.forecast4}}</td>
        <td>{{favorite2.forecast5}}</td>
        <td>{{favorite2.forecast6}}</td>
        <td>{{favorite2.forecast7}}</td>
        <td>{{favorite2.forecast8}}</td>
        <td>{{favorite2.forecast9}}</td>
        <td>{{favorite2.forecast10}}</td>
        <td>{{favorite2.forecast11}}</td>
        <td>{{favorite2.forecast12}}</td>
        <td>{{favorite2.forecast13}}</td>
      </tr>
      <tr>
        <th scope="row">{{ current_user.fav3 }}</th>
        <td>{{favorite3.forecast0}}</td>
        <td>{{favorite3.forecast1}}</td>
        <td>{{favorite3.forecast2}}</td>
        <td>{{favorite3.forecast3}}</td>
        <td>{{favorite3.forecast4}}</td>
        <td>{{favorite3.forecast5}}</td>
        <td>{{favorite3.forecast6}}</td>
        <td>{{favorite3.forecast7}}</td>
        <td>{{favorite3.forecast8}}</td>
        <td>{{favorite3.forecast9}}</td>
        <td>{{favorite3.forecast10}}</td>
        <td>{{favorite3.forecast11}}</td>
        <td>{{favorite3.forecast12}}</td>
        <td>{{favorite3.forecast13}}</td>
      </tr>
      <tr>
        <th scope="row">{{ current_user.fav4 }}</th>
        <td>{{favorite4.forecast0}}</td>
        <td>{{favorite4.forecast1}}</td>
        <td>{{favorite4.forecast2}}</td>
        <td>{{favorite4.forecast3}}</td>
        <td>{{favorite4.forecast4}}</td>
        <td>{{favorite4.forecast5}}</td>
        <td>{{favorite4.forecast6}}</td>
        <td>{{favorite4.forecast7}}</td>
        <td>{{favorite4.forecast8}}</td>
        <td>{{favorite4.forecast9}}</td>
        <td>{{favorite4.forecast10}}</td>
        <td>{{favorite4.forecast11}}</td>
        <td>{{favorite4.forecast12}}</td>
        <td>{{favorite4.forecast13}}</td>
      </tr>
      {%if (current_user.ikon == 1)%}
      <tr>
        <th scope="row">{{deepIkon.name}}</th>
        <td>{{deepIkon.forecast0}}</td>
        <td>{{deepIkon.forecast1}}</td>
        <td>{{deepIkon.forecast2}}</td>
        <td>{{deepIkon.forecast3}}</td>
        <td>{{deepIkon.forecast4}}</td>
        <td>{{deepIkon.forecast5}}</td>
        <td>{{deepIkon.forecast6}}</td>
        <td>{{deepIkon.forecast7}}</td>
        <td>{{deepIkon.forecast8}}</td>
        <td>{{deepIkon.forecast9}}</td>
        <td>{{deepIkon.forecast10}}</td>
        <td>{{deepIkon.forecast11}}</td>
        <td>{{deepIkon.forecast12}}</td>
        <td>{{deepIkon.forecast13}}</td>
      </tr>
      {%endif%}
      {%if (current_user.epic == 1)%}
      <tr>
        <th scope="row">{{deepEpic.name}}</th>
        <td>{{deepEpic.forecast0}}</td>
        <td>{{deepEpic.forecast1}}</td>
        <td>{{deepEpic.forecast2}}</td>
        <td>{{deepEpic.forecast3}}</td>
        <td>{{deepEpic.forecast4}}</td>
        <td>{{deepEpic.forecast5}}</td>
        <td>{{deepEpic.forecast6}}</td>
        <td>{{deepEpic.forecast7}}</td>
        <td>{{deepEpic.forecast8}}</td>
        <td>{{deepEpic.forecast9}}</td>
        <td>{{deepEpic.forecast10}}</td>
        <td>{{deepEpic.forecast11}}</td>
        <td>{{deepEpic.forecast12}}</td>
        <td>{{deepEpic.forecast13}}</td>
      </tr>
      {%endif%}
      {%if (current_user.mc == 1)%}
        <tr>
          <th scope="row">{{deepMC.name}}</th>
          <td>{{deepMC.forecast0}}</td>
          <td>{{deepMC.forecast1}}</td>
          <td>{{deepMC.forecast2}}</td>
          <td>{{deepMC.forecast3}}</td>
          <td>{{deepMC.forecast4}}</td>
          <td>{{deepMC.forecast5}}</td>
          <td>{{deepMC.forecast6}}</td>
          <td>{{deepMC.forecast7}}</td>
          <td>{{deepMC.forecast8}}</td>
          <td>{{deepMC.forecast9}}</td>
          <td>{{deepMC.forecast10}}</td>
          <td>{{deepMC.forecast11}}</td>
          <td>{{deepMC.forecast12}}</td>
          <td>{{deepMC.forecast13}}</td>
        </tr>
        {%endif%}
        {%if (current_user.powder == 1)%}
        <tr>
            <th scope="row">{{deepPowder.name}}</th>
            <td>{{deepPowder.forecast0}}</td>
            <td>{{deepPowder.forecast1}}</td>
            <td>{{deepPowder.forecast2}}</td>
            <td>{{deepPowder.forecast3}}</td>
            <td>{{deepPowder.forecast4}}</td>
            <td>{{deepPowder.forecast5}}</td>
            <td>{{deepPowder.forecast6}}</td>
            <td>{{deepPowder.forecast7}}</td>
            <td>{{deepPowder.forecast8}}</td>
            <td>{{deepPowder.forecast9}}</td>
            <td>{{deepPowder.forecast10}}</td>
            <td>{{deepPowder.forecast11}}</td>
            <td>{{deepPowder.forecast12}}</td>
            <td>{{deepPowder.forecast13}}</td>
          </tr>
        {%endif%}
        {%if (current_user.indy == 1)%}
        <tr>
            <th scope="row">{{deepIndy.name}}</th>
            <td>{{deepIndy.forecast0}}</td>
            <td>{{deepIndy.forecast1}}</td>
            <td>{{deepIndy.forecast2}}</td>
            <td>{{deepIndy.forecast3}}</td>
            <td>{{deepIndy.forecast4}}</td>
            <td>{{deepIndy.forecast5}}</td>
            <td>{{deepIndy.forecast6}}</td>
            <td>{{deepIndy.forecast7}}</td>
            <td>{{deepIndy.forecast8}}</td>
            <td>{{deepIndy.forecast9}}</td>
            <td>{{deepIndy.forecast10}}</td>
            <td>{{deepIndy.forecast11}}</td>
            <td>{{deepIndy.forecast12}}</td>
            <td>{{deepIndy.forecast13}}</td>
            </tr>
            {%endif%}
    </tbody>
  </table>
  <div style="text-align: right">
    <a
      class="btn btn-primary"
      href="{{ url_for('views.setfavorites') }}"
      role="button"
      >Set Favorites</a
    >
  </div>
</div>
<script src="{{ url_for('static', filename='javascript/dateIncrement.js') }}">// calculates future dates</script>
{% endblock %}

webApp/website/templates/login.html
{% extends "base.html" %} {% block title %} Login {% endblock %} {% block
    content %}
    <div>
        <div style="text-align: center">
      <a href="#"
        ><img
          src="{{url_for('static', filename='logo.png')}}"
          width="500"
          height="500"
      /></a></div>
      <br />
      <br />
      <h2>Login</h3>
      <br />
      <div class="form-group">
        <form method="POST">
          <label for="email">Email Address</label>
          <input
            type="email"
            class="form-control"
            id="email"
            name="email"
            placeholder="Enter Email"
          />
          <label for="password">Password</label>
          <input
            type="password"
            class="form-control"
            id="password"
            name="password"
            placeholder="Enter Password"
          />
          <br />
          <div style="text-align: right;">
          <button  type="submit" class="btn btn-primary btn-lg" >Login</button>
        </div>
        </form>
      </div>
    </div>
    {% endblock %}
    